// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgEA9ssv-dRTIC1JUG2Hv3kpgLI8tVeoU',
    appId: '1:979507034274:web:961a2af173947a935bfffb',
    messagingSenderId: '979507034274',
    projectId: 'skindisease-abe93',
    authDomain: 'skindisease-abe93.firebaseapp.com',
    storageBucket: 'skindisease-abe93.firebasestorage.app',
    measurementId: 'G-G38TXCPNVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaJFZM14KQZ6K0VHWW2yJcfVGL5Qeg_Kg',
    appId: '1:979507034274:android:83256a9c64200e385bfffb',
    messagingSenderId: '979507034274',
    projectId: 'skindisease-abe93',
    storageBucket: 'skindisease-abe93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4h7bfTxDaJAIhJpE5WDwp2WnC7RoqvM',
    appId: '1:979507034274:ios:51543cd7e1480a705bfffb',
    messagingSenderId: '979507034274',
    projectId: 'skindisease-abe93',
    storageBucket: 'skindisease-abe93.firebasestorage.app',
    iosBundleId: 'com.example.skinai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgEA9ssv-dRTIC1JUG2Hv3kpgLI8tVeoU',
    appId: '1:979507034274:web:961a2af173947a935bfffb',
    messagingSenderId: '979507034274',
    projectId: 'skindisease-abe93',
    authDomain: 'skindisease-abe93.firebaseapp.com',
    storageBucket: 'skindisease-abe93.firebasestorage.app',
    measurementId: 'G-G38TXCPNVT',
  );

}